必备线性代数知识

标量

简单操作：
c = a + b
c = a * b
c = sin a

长度：
a大于0时，a的绝对值 = a
a小于等于0时，a的绝对值 = -a
a + b的绝对值 <= a的绝对值 + b的绝对值
a * b的绝对值 = a的绝对值 * b的绝对值

向量
## 简单操作

$c = a + b \quad \text{where } c_i = a_i + b_i$

$c = \alpha \cdot b \quad \text{where } c_i = \alpha b_i$

$c = \sin a \quad \text{where } c_i = \sin a_i$

---

## 长度

$$
\|a\|_2 =
\left(
\sum_{i=1}^{m} a_i^2
\right)^{\frac{1}{2}}
$$

$$
\|a\| \ge 0 \quad \text{for all } a
$$

$$
\|a + b\| \le \|a\| + \|b\|
$$

$$
\|\alpha b\| = |\alpha| \cdot \|b\|
$$
​	
 ## 点乘（内积）

向量 $a$ 和 $b$ 的点乘定义为：

$$
a^T b = \sum_{i=1}^{n} a_i b_i
$$

---

## 正交

如果

$$
a^T b = \sum_{i=1}^{n} a_i b_i = 0
$$

则称向量 $a$ 与 $b$ 正交（orthogonal）。



# 矩阵

## 简单操作

### 1️⃣ 矩阵加法
$$
C = A + B
$$
$$
C_{ij} = A_{ij} + B_{ij}
$$

---

### 2️⃣ 数乘
$$
C = \alpha B
$$
$$
C_{ij} = \alpha B_{ij}
$$

---

### 3️⃣ 逐元素函数
$$
C = \sin A
$$
$$
C_{ij} = \sin A_{ij}
$$




# 矩阵

## 矩阵乘法

设

$$
A \in \mathbb{R}^{m \times n}, \quad
B \in \mathbb{R}^{n \times p}
$$

则

$$
C = AB \in \mathbb{R}^{m \times p}
$$

其中

$$
C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}
$$




# 矩阵范数（Matrix Norm）

---

## 1️⃣ 基本关系

设

$$
c = A b
$$

则有

$$
\|c\| \le \|A\| \, \|b\|
$$

这表示：  
矩阵 $A$ 作为一个线性变换，对向量 $b$ 的长度放大是有上界的。

---

## 2️⃣ 矩阵范数的定义

矩阵范数定义为：

> 满足
>
> $$
> \|A b\| \le \|A\| \|b\|
> $$
>
> 的**最小常数**。

等价地，可以写成：

$$
\|A\| = \sup_{b \ne 0}
\frac{\|A b\|}{\|b\|}
$$

含义：

矩阵范数表示线性变换的**最大伸缩倍数**。

---

## 3️⃣ 常见矩阵范数

### ① 诱导 2-范数（Operator Norm）

$$
\|A\|_2 =
\sup_{b \ne 0}
\frac{\|A b\|_2}{\|b\|_2}
$$

它等于矩阵的**最大奇异值**。

---

### ② Frobenius 范数

$$
\|A\|_F =
\left(
\sum_{i,j} A_{ij}^2
\right)^{\frac{1}{2}}
$$

含义：

把矩阵看作一个大向量，计算其欧几里得长度。

---

## 4️⃣ 直观理解

- 向量范数：向量有多长  
- 矩阵范数：矩阵最多能把向量拉长多少倍  
- 若 $\|A\| > 1$：可能放大  
- 若 $\|A\| < 1$：整体收缩  

---

## 5️⃣ 与深度学习的关系

神经网络一层：

$$
x_{l+1} = W x_l
$$

若

$$
\|W\| > 1
$$

可能导致梯度爆炸；

若

$$
\|W\| < 1
$$

可能导致梯度消失。





# 特殊矩阵

---

## 1️⃣ 对称矩阵（Symmetric Matrix）

矩阵 $A$ 称为对称矩阵，如果：

$$
A = A^T
$$

等价地：

$$
A_{ij} = A_{ji}
$$

含义：

矩阵关于主对角线对称。

---

## 2️⃣ 反对称矩阵（Skew-Symmetric Matrix）

矩阵 $A$ 称为反对称矩阵，如果：

$$
A = -A^T
$$

等价地：

$$
A_{ij} = -A_{ji}
$$

性质：

- 主对角线元素必须为 0
- $A_{ii} = 0$

---

## 3️⃣ 正定矩阵（Positive Definite Matrix）

向量的平方范数：

$$
\|x\|^2 = x^T x \ge 0
$$

推广到矩阵：

$$
x^T A x \ge 0
$$

若对所有 $x \ne 0$ 都满足：

$$
x^T A x > 0
$$

则称 $A$ 为 **正定矩阵**。

---

## 4️⃣ 直观理解

- 对称矩阵：关于主对角线镜像对称  
- 反对称矩阵：对角线为 0，上下符号相反  
- 正定矩阵：二次型始终非负（或严格正）

---

## 5️⃣ 重要性质

对于对称矩阵：

- 所有特征值为实数  
- 若所有特征值 > 0，则矩阵正定  
- 若所有特征值 ≥ 0，则矩阵半正定  

---

## 6️⃣ 与深度学习的关系

- 协方差矩阵一定是半正定  
- Hessian 矩阵正定 ⇒ 极小值点  
- 正定矩阵保证优化问题是凸的

# 正交矩阵与置换矩阵

---

## 1️⃣ 正交矩阵（Orthogonal Matrix）

矩阵 $U$ 称为正交矩阵，如果：

- 所有行向量彼此正交  
- 所有行向量长度为 1  

数学表达为：

$$
\sum_j U_{ij} U_{kj} = \delta_{ik}
$$

其中 $\delta_{ik}$ 是 Kronecker delta：

$$
\delta_{ik} =
\begin{cases}
1, & i = k \\
0, & i \ne k
\end{cases}
$$

---

### 等价表达

正交矩阵可以写成：

$$
U U^T = I
$$

等价地：

$$
U^T U = I
$$

因此：

$$
U^{-1} = U^T
$$

---

### 直观理解

正交矩阵表示：

- 旋转
- 翻转

不会改变向量长度。

$$
\|Ux\| = \|x\|
$$

---

## 2️⃣ 置换矩阵（Permutation Matrix）

置换矩阵 $P$ 定义为：

$$
P_{ij} = 1 \quad \text{当且仅当 } j = \pi(i)
$$

其中 $\pi$ 是一个排列（permutation）。

---

### 性质

- 每一行只有一个 1  
- 每一列只有一个 1  
- 其余元素为 0  

---

### 重要性质

置换矩阵是正交矩阵：

$$
P P^T = I
$$

因此：

$$
P^{-1} = P^T

# 二、特征值与特征向量（Eigenvalues & Eigenvectors）

## 定义

对于矩阵 $A$，如果存在非零向量 $x$ 和标量 $\lambda$ 使得：

$$
A x = \lambda x
$$

则：

- $\lambda$ 称为特征值  
- $x$ 称为特征向量  

---

## 含义

矩阵作用在特征向量上：

- 不改变方向  
- 只改变长度  

放大或缩小倍数为：

$$
\lambda
$$

---

## 求特征值

由

$$
A x = \lambda x
$$

得到

$$
(A - \lambda I)x = 0
$$

要有非零解，必须满足：

$$
\det(A - \lambda I) = 0
$$

这称为特征方程。

---

## 几何意义

- 特征向量是“不会被旋转的方向”
- 特征值表示沿该方向的伸缩比例

---

## 与矩阵范数的关系

矩阵的 2-范数等于：

$$
\|A\|_2 = \text{最大奇异值}
$$

若 $A$ 是对称矩阵，则：

$$
\|A\|_2 = \max |\lambda_i|
$$

---

## 正定矩阵与特征值

对于对称矩阵：

- 若所有特征值 > 0 → 正定  
- 若所有特征值 ≥ 0 → 半正定  

---

以下是pytorch实现：

标量

In [41]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x + y, x - y, x * y, x/y

(tensor([5.]), tensor([1.]), tensor([6.]), tensor([1.5000]))

向量

In [42]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.arange(4)
x, y, x[2], y[3]

(tensor([1., 2., 3.]), tensor([0, 1, 2, 3]), tensor(3.), tensor(3))

矩阵

In [43]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

转置矩阵

In [44]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵

In [45]:
B = torch.tensor([[0.0, 1.0, 2.0], [1.0, 4.0, 5.0], [2.0, 5.0, 8.0]])
B, B == B.T

(tensor([[0., 1., 2.],
         [1., 4., 5.],
         [2., 5., 8.]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构

In [46]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

用.clone()可以分配新内存

In [47]:
Y = X.clone()
Y

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [48]:
2 + Y, Y * 10, Y.sum()

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[  0,  10,  20,  30],
          [ 40,  50,  60,  70],
          [ 80,  90, 100, 110]],
 
         [[120, 130, 140, 150],
          [160, 170, 180, 190],
          [200, 210, 220, 230]]]),
 tensor(276))

.sum()默认计算全部维度的和

In [49]:
X = torch.arange(20 * 2).reshape(2, 5, 4)
X, X.sum(), X.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 tensor(780),
 torch.Size([2, 5, 4]))

还可以对某个维度或者某几个维度求和

In [50]:
X.sum(axis=0), X.sum(axis=0).shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [51]:
X.sum(axis=[0, 1]), X.sum(axis=[0, 1]).shape

(tensor([180, 190, 200, 210]), torch.Size([4]))

求平均数.mean()

In [52]:
X = X.to(torch.float32)
X.mean()

tensor(19.5000)

In [53]:
X.mean(axis=0)

tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])

计算总和和均值的时候保持轴数不变

In [54]:
sum_X = X.sum(axis=0, keepdims=True)
sum_X

tensor([[[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [55]:
X/sum_X

tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
         [0.1429, 0.1667, 0.1875, 0.2059],
         [0.2222, 0.2368, 0.2500, 0.2619],
         [0.2727, 0.2826, 0.2917, 0.3000],
         [0.3077, 0.3148, 0.3214, 0.3276]],

        [[1.0000, 0.9545, 0.9167, 0.8846],
         [0.8571, 0.8333, 0.8125, 0.7941],
         [0.7778, 0.7632, 0.7500, 0.7381],
         [0.7273, 0.7174, 0.7083, 0.7000],
         [0.6923, 0.6852, 0.6786, 0.6724]]])

按轴求前缀和

In [56]:
X.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

向量点积

In [57]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])
torch.dot(x, y)

tensor(32.)

矩阵乘向量和矩阵乘法

In [58]:
x = torch.arange(12).reshape(3, 4)
y1 = torch.arange(1,5)
y2 = torch.arange(12).reshape(4, 3)
x, y1, y2, torch.mv(x, y1), torch.mm(x, y2) 

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([1, 2, 3, 4]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([ 20,  60, 100]),
 tensor([[ 42,  48,  54],
         [114, 136, 158],
         [186, 224, 262]]))

L1范数是向量元素的绝对值之和

In [59]:
u = torch.tensor([0.0, 3.0, -4.0])
torch.abs(u).sum()

tensor(7.)

L2范数是向量平方和的平方根

In [60]:
u = torch.tensor([0.0, 3.0, -4.0])
u.norm()

tensor(5.)

F范数是对矩阵而言的:他是矩阵元素的平方和的平方根

In [61]:
torch.norm(torch.ones((4, 9)))

tensor(6.)